### ISSUE TITLE
Error compiling reason files

### ISSUE THREAD

**Issue by mrkaspa** [cxa/ppx_bsx#1]
Avoid to process reason files

```
File "/Users/mrkaspa/code/my-react-app/src/demo.re", line 8, characters 5-89:
Error: Unbound value div
ninja: build stopped: subcommand failed.
>>>> Finish compiling
```

**Comment by cxa** [comment]
Could you provide more details? e.g. your code snippets.

**Comment by mrkaspa** [comment]
I created a reason react project and changed one component to ocaml, enabled this ppx but it threw errors with jsx in a  reason file

**Comment by cxa** [comment]
Does your Reason or OCaml file has something like 

```OCaml
[%bsx "<div>hello</div>"]
````

If not, this should be other issues not related to this ppx.

**Comment by mrkaspa** [comment]
yes it does

**Comment by cxa** [comment]
Could you post your `[%bsx "..."]`? The error is too opaque.

**Comment by cxa** [comment]
Closed due to inactivity.
